### ISSUE TITLE
Calculation of D is biased toward 'Mark Up'

### ISSUE THREAD

**Issue by aclaycomb-usgs** [usgs/geomag-baseline-calculator#250]
- Correct calculation of geographicMeridian in BaselineCalculator and ObservationBaselineCalculator
- Correct/Add unit tests.

**Comment by jmfee-usgs** [comment]
> 5) The Mean Mark (MM) is computed by averaging all of the Mark Up and Mark Down measurements in steps 1 and 3.

As I recall it's not supposed to be a direct average, but rather the average of mark up and (mark down +/- 180).


Including references to the code where available may also be useful.  If you look at source files via github, you can click on a line number then copy the url from the browser address bar.  For example, the observation "geographic meridian" function is at:
https://github.com/usgs/geomag-baseline-calculator/blob/master/src/htdocs/js/geomag/ObservationBaselineCalculator.js#L120

and the raw "geographic meridian" function is at:
https://github.com/usgs/geomag-baseline-calculator/blob/master/src/htdocs/js/geomag/BaselineCalculator.js#L84

**Comment by aclaycomb-usgs** [comment]
I'll ask bill again, and that's what I'll put in the 'fix,' but the line 5) you quote is what bill etc are sticking by.  maybe that has something to do with the way magneticAzimuthMark works

**Comment by aclaycomb-usgs** [comment]
https://github.com/usgs/geomag-baseline-calculator/blob/master/src/htdocs/js/geomag/BaselineCalculator.js#L146

**Comment by jmfee-usgs** [comment]
Original description, preserving:

Computing the Absolute value of D is done as follows:

1)	Measurements of Mark Up and Mark Down are performed.
2)	Four D readings are performed and are termed West Down, East Down, West Up, and East Up.  These refer to the orientations of the telescope.
3)	Measurements of Mark Up and Mark Down are repeated.
4)	The magnetic south meridian (MSM) is computed by averaging the four D measurements in step 2.
5)	The Mean Mark (MM) is computed by averaging all of the Mark Up and Mark Down measurements in steps 1 and 3.
6)	The Magnetic Azimuth of the Mark (MAZ) is computed as MAZ = MM – MSM + 90°.
7)	D is then computed as D = TA – MAZ - 180° where TA is the True Azimuth.  The True Azimuth is measured independently and does not change often (timescale of years).  This computation is usually done in decimal degrees.

In Observation Baseline Calculator 'Geographic Meridian' (a term not found in the original 'algorithm,' included in the document below, and quoted above), but as a start I suggest averaging over the four mark values in the ObservationBaselineCalculator.js' geographicMeridian() function, instead of just the two mark up values as is currently done.

As of the writing of this issue, the 'algorithm' as understood by the issue submitter is:

1) get First Mark Up, First Mark Down from Reading
2) get West Down, East Down, West Up, East Up from Reading
3) get Second Mark Up, Second Mark Down from Reading
4) get declination_shift from Reading
5) trueAzimuthMark = function( Default = 0)  <- may get pulled from the database somewhere in another .js, like ObservatoryFactory.js, when loaded in the .php/.js mess
6) geographic Meridian = mean( First Mark Up, Second Mark Up) - trueAzimuthMark
7) magnetic south meridian = mean( West Down, West Up, East Down, East Up)
8) magneticDeclination =magneticSouthMeridian - geographicMeridian
9) if magneticDeclination is > 90 degrees, repeatedly subtract 180 degrees until it isn't
10) if magneticDeclination is <= -90 degrees, repeatedly add 180 degrees until it isn't
11) magneticDeclination = magneticDeclination + declination_shift

I'm fairly confident these accomplish a similar thing, but I just don't want to get the terminology confused.  There are functions for MeanAzimuthMark in the .js, but they appear to go unused...
So, I'll make the assumption that geographicMeridian = Mean Mark = mean(FMU, FMD, SMU, SMD) won't break anything... we'll see if that works out going forward.

[Web Absolutes Issues.docx](https://github.com/usgs/geomag-baseline-calculator/files/423828/Web.Absolutes.Issues.docx)
